services:
  db:
    image: docker.io/library/postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Production DB volume
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # In production, we assume the image is built and tagged.
    # For now, we build it from context to ensure it works in this repo structure.
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ARBO_DATA_ROOT=/data
      - ARBO_NEXTCLOUD_ROOT=/mnt/nextcloud
      - ARBO_RUN_MIGRATIONS=1 # In prod, auto-migrate? Maybe safe for MVP.
      - ARBO_RUN_SEED=0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      # 1. Workspace Data (Persisted)
      - arbo_data:/data:Z

      # 2. Nextcloud Assets (ReadOnly)
      - ${ARBO_NEXTCLOUD_DIR}:/mnt/nextcloud:ro,z

      # NO source code mounts here. This is the key difference.
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  arbo_data:
